# Lab | Web Scraping

Welcome to the "Books to Scrape" Web Scraping Adventure Lab!

**Objective**

In this lab, we will embark on a mission to unearth valuable insights from the data available on Books to Scrape, an online platform showcasing a wide variety of books. As data analyst, you have been tasked with scraping a specific subset of book data from Books to Scrape to assist publishing companies in understanding the landscape of highly-rated books across different genres. Your insights will help shape future book marketing strategies and publishing decisions.

**Background**

In a world where data has become the new currency, businesses are leveraging big data to make informed decisions that drive success and profitability. The publishing industry, much like others, utilizes data analytics to understand market trends, reader preferences, and the performance of books based on factors such as genre, author, and ratings. Books to Scrape serves as a rich source of such data, offering detailed information about a diverse range of books, making it an ideal platform for extracting insights to aid in informed decision-making within the literary world.

**Task**

Your task is to create a Python script using BeautifulSoup and pandas to scrape Books to Scrape book data, focusing on book ratings and genres. The script should be able to filter books with ratings above a certain threshold and in specific genres. Additionally, the script should structure the scraped data in a tabular format using pandas for further analysis.

**Expected Outcome**

A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`. The function should scrape book data from the "Books to Scrape" website and return a `pandas` DataFrame with the following columns:

**Expected Outcome**

- A function named `scrape_books` that takes two parameters: `min_rating` and `max_price`.
- The function should return a DataFrame with the following columns:
  - **UPC**: The Universal Product Code (UPC) of the book.
  - **Title**: The title of the book.
  - **Price (£)**: The price of the book in pounds.
  - **Rating**: The rating of the book (1-5 stars).
  - **Genre**: The genre of the book.
  - **Availability**: Whether the book is in stock or not.
  - **Description**: A brief description or product description of the book (if available).
  
You will execute this script to scrape data for books with a minimum rating of `4.0 and above` and a maximum price of `£20`. 

Remember to experiment with different ratings and prices to ensure your code is versatile and can handle various searches effectively!

**Resources**

- [Beautiful Soup Documentation](https://www.crummy.com/software/BeautifulSoup/bs4/doc/)
- [Pandas Documentation](https://pandas.pydata.org/pandas-docs/stable/index.html)
- [Books to Scrape](https://books.toscrape.com/)

**Hint**

Your first mission is to familiarize yourself with the **Books to Scrape** website. Navigate to [Books to Scrape](http://books.toscrape.com/) and explore the available books to understand their layout and structure. 

Next, think about how you can set parameters for your data extraction:

- **Minimum Rating**: Focus on books with a rating of 4.0 and above.
- **Maximum Price**: Filter for books priced up to £20.

After reviewing the site, you can construct a plan for scraping relevant data. Pay attention to the details displayed for each book, including the title, price, rating, and availability. This will help you identify the correct HTML elements to target with your scraping script.

Make sure to build your scraping URL and logic based on the patterns you observe in the HTML structure of the book listings!


---

**Best of luck! Immerse yourself in the world of books, and may the data be with you!**

**Important Note**:

In the fast-changing online world, websites often update and change their structures. When you try this lab, the **Books to Scrape** website might differ from what you expect.

If you encounter issues due to these changes, like new rules or obstacles preventing data extraction, don’t worry! Get creative.

You can choose another website that interests you and is suitable for scraping data. Options like Wikipedia, The New York Times, or even library databases are great alternatives. The main goal remains the same: extract useful data and enhance your web scraping skills while exploring a source of information you enjoy. This is your opportunity to practice and adapt to different web environments!

def scrape_books (min_rating, max_price): 
    1. request webpage 
    2. parse html 
    3. extract book blocks 
    4. loop thrpugh books 
    5. extract fields 
    6. clean convert data
    7. filter by rating and price 4.0 and above + max of 20 pounds 
    8. return datafrma 

find all books
    ↓
for each book:
    extract basic info
    go to detail page
    extract extra info
    store in list
    ↓
convert to DataFrame

In [2]:
import requests
from bs4 import BeautifulSoup
# selenium
#playwright 

import pandas as pd
from time import sleep

In [3]:
books = [] 
# a list for columns, and then append a dict for every book with date of every column

In [4]:
soup = BeautifulSoup()

In [5]:
url = "https://books.toscrape.com/"
response = requests.get(url)
response

In [6]:
response.content

b'<!DOCTYPE html>\n<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->\n<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->\n<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->\n<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->\n    <head>\n        <title>\n    All products | Books to Scrape - Sandbox\n</title>\n\n        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />\n        <meta name="created" content="24th Jun 2016 09:29" />\n        <meta name="description" content="" />\n        <meta name="viewport" content="width=device-width" />\n        <meta name="robots" content="NOARCHIVE,NOCACHE" />\n\n        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->\n        <!--[if lt IE 9]>\n        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>\n        <![endif]-->\n\n        \n            <link rel="shortcut icon" href="static/oscar/favicon.ico" />\n        \n\n        \n        \n    \n    \n        <link rel="stylesheet" type="text/css" href="static/oscar/css/styles.css" />\n    \n    <link rel="stylesheet" href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" />\n    <link rel="stylesheet" type="text/css" href="static/oscar/css/datetimepicker.css" />\n\n\n        \n        \n\n        \n\n        \n            \n            \n\n        \n    </head>\n\n    <body id="default" class="default">\n        \n        \n    \n    \n    <header class="header container-fluid">\n        <div class="page_inner">\n            <div class="row">\n                <div class="col-sm-8 h1"><a href="index.html">Books to Scrape</a><small> We love being scraped!</small>\n</div>\n\n                \n            </div>\n        </div>\n    </header>\n\n    \n    \n<div class="container-fluid page">\n    <div class="page_inner">\n        \n    <ul class="breadcrumb">\n        <li>\n            <a href="index.html">Home</a>\n        </li>\n        <li class="active">All products</li>\n    </ul>\n\n        <div class="row">\n\n            <aside class="sidebar col-sm-4 col-md-3">\n                \n                <div id="promotions_left">\n                    \n                </div>\n                \n    \n    \n        \n        <div class="side_categories">\n            <ul class="nav nav-list">\n                \n                    <li>\n                        <a href="catalogue/category/books_1/index.html">\n                            \n                                Books\n                            \n                        </a>\n\n                        <ul>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/travel_2/index.html">\n                            \n                                Travel\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/mystery_3/index.html">\n                            \n                                Mystery\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/historical-fiction_4/index.html">\n                            \n                                Historical Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/sequential-art_5/index.html">\n                            \n                                Sequential Art\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/classics_6/index.html">\n                            \n                                Classics\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/philosophy_7/index.html">\n                            \n                                Philosophy\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/romance_8/index.html">\n                            \n                                Romance\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/womens-fiction_9/index.html">\n                            \n                                Womens Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/fiction_10/index.html">\n                            \n                                Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/childrens_11/index.html">\n                            \n                                Childrens\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/religion_12/index.html">\n                            \n                                Religion\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/nonfiction_13/index.html">\n                            \n                                Nonfiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/music_14/index.html">\n                            \n                                Music\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/default_15/index.html">\n                            \n                                Default\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/science-fiction_16/index.html">\n                            \n                                Science Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/sports-and-games_17/index.html">\n                            \n                                Sports and Games\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/add-a-comment_18/index.html">\n                            \n                                Add a comment\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/fantasy_19/index.html">\n                            \n                                Fantasy\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/new-adult_20/index.html">\n                            \n                                New Adult\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/young-adult_21/index.html">\n                            \n                                Young Adult\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/science_22/index.html">\n                            \n                                Science\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/poetry_23/index.html">\n                            \n                                Poetry\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/paranormal_24/index.html">\n                            \n                                Paranormal\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/art_25/index.html">\n                            \n                                Art\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/psychology_26/index.html">\n                            \n                                Psychology\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/autobiography_27/index.html">\n                            \n                                Autobiography\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/parenting_28/index.html">\n                            \n                                Parenting\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/adult-fiction_29/index.html">\n                            \n                                Adult Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/humor_30/index.html">\n                            \n                                Humor\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/horror_31/index.html">\n                            \n                                Horror\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/history_32/index.html">\n                            \n                                History\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/food-and-drink_33/index.html">\n                            \n                                Food and Drink\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/christian-fiction_34/index.html">\n                            \n                                Christian Fiction\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/business_35/index.html">\n                            \n                                Business\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/biography_36/index.html">\n                            \n                                Biography\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/thriller_37/index.html">\n                            \n                                Thriller\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/contemporary_38/index.html">\n                            \n                                Contemporary\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/spirituality_39/index.html">\n                            \n                                Spirituality\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/academic_40/index.html">\n                            \n                                Academic\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/self-help_41/index.html">\n                            \n                                Self Help\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/historical_42/index.html">\n                            \n                                Historical\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/christian_43/index.html">\n                            \n                                Christian\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/suspense_44/index.html">\n                            \n                                Suspense\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/short-stories_45/index.html">\n                            \n                                Short Stories\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/novels_46/index.html">\n                            \n                                Novels\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/health_47/index.html">\n                            \n                                Health\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/politics_48/index.html">\n                            \n                                Politics\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/cultural_49/index.html">\n                            \n                                Cultural\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/erotica_50/index.html">\n                            \n                                Erotica\n                            \n                        </a>\n\n                        </li>\n                        \n                \n                    <li>\n                        <a href="catalogue/category/books/crime_51/index.html">\n                            \n                                Crime\n                            \n                        </a>\n\n                        </li>\n                        \n                            </ul></li>\n                        \n                \n            </ul>\n        </div>\n    \n    \n\n            </aside>\n\n            <div class="col-sm-8 col-md-9">\n                \n                <div class="page-header action">\n                    <h1>All products</h1>\n                </div>\n                \n\n                \n\n\n\n<div id="messages">\n\n</div>\n\n\n                <div id="promotions">\n                    \n                </div>\n\n                \n    <form method="get" class="form-horizontal">\n        \n        <div style="display:none">\n            \n            \n        </div>\n\n        \n            \n                \n                    <strong>1000</strong> results - showing <strong>1</strong> to <strong>20</strong>.\n                \n            \n            \n        \n    </form>\n    \n        <section>\n            <div class="alert alert-warning" role="alert"><strong>Warning!</strong> This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.</div>\n\n            <div>\n                <ol class="row">\n                    \n             

In [7]:
response.headers

{'Date': 'Sat, 27 Jun 2026 10:05:50 GMT', 'Content-Type': 'text/html', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Last-Modified': 'Wed, 08 Feb 2023 21:02:32 GMT', 'ETag': 'W/"63e40de8-c85e"', 'Strict-Transport-Security': 'max-age=0; includeSubDomains; preload', 'Content-Encoding': 'br'}

In [8]:
soup = BeautifulSoup(response.content, "html.parser")

In [9]:
type (soup)

bs4.BeautifulSoup

In [10]:
print (soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   All products | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="index.html">
       Home
      </a>
     </li>
     <li class="active">
      All products
     </li>
    </ul>
    <div class="row">
     <aside class="sidebar col-sm-4 col-md-3">
      <div id="promotions_left">
      </div>
      <div class="side_categories">
       <ul class="nav nav-list">
        <li>
         <a href="catalogue/category/books_1/index.html">
          Books
         </a>
         <ul>
          <li>
           <a href="catalogue/category/books/travel_2/index.html">
            Travel
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/mystery_3/index.html">
            Mystery
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical-fiction_4/index.html">
            Historical Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sequential-art_5/index.html">
            Sequential Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/classics_6/index.html">
            Classics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/philosophy_7/index.html">
            Philosophy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/romance_8/index.html">
            Romance
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/womens-fiction_9/index.html">
            Womens Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fiction_10/index.html">
            Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/childrens_11/index.html">
            Childrens
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/religion_12/index.html">
            Religion
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/nonfiction_13/index.html">
            Nonfiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/music_14/index.html">
            Music
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/default_15/index.html">
            Default
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science-fiction_16/index.html">
            Science Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/sports-and-games_17/index.html">
            Sports and Games
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/add-a-comment_18/index.html">
            Add a comment
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/fantasy_19/index.html">
            Fantasy
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/new-adult_20/index.html">
            New Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/young-adult_21/index.html">
            Young Adult
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/science_22/index.html">
            Science
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/poetry_23/index.html">
            Poetry
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/paranormal_24/index.html">
            Paranormal
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/art_25/index.html">
            Art
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/psychology_26/index.html">
            Psychology
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/autobiography_27/index.html">
            Autobiography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/parenting_28/index.html">
            Parenting
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/adult-fiction_29/index.html">
            Adult Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/humor_30/index.html">
            Humor
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/horror_31/index.html">
            Horror
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/history_32/index.html">
            History
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/food-and-drink_33/index.html">
            Food and Drink
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian-fiction_34/index.html">
            Christian Fiction
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/business_35/index.html">
            Business
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/biography_36/index.html">
            Biography
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/thriller_37/index.html">
            Thriller
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/contemporary_38/index.html">
            Contemporary
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/spirituality_39/index.html">
            Spirituality
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/academic_40/index.html">
            Academic
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/self-help_41/index.html">
            Self Help
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/historical_42/index.html">
            Historical
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/christian_43/index.html">
            Christian
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/suspense_44/index.html">
            Suspense
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/short-stories_45/index.html">
            Short Stories
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/novels_46/index.html">
            Novels
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/health_47/index.html">
            Health
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/politics_48/index.html">
            Politics
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/cultural_49/index.html">
            Cultural
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/erotica_50/index.html">
            Erotica
           </a>
          </li>
          <li>
           <a href="catalogue/category/books/crime_51/index.html">
            Crime
           </a>
          </li>
         </ul>
        </li>
       </ul>
      </div>
     </aside>
     <div class="col-sm-8 col-md-9">
      <div class="page-header action">
       <h1>
        All products
       </h1>
      </div>
      <div id="messages">
      </div>
      <div id="promotions">
      </div>
      <form class="form-horizontal" method="get">
       <div style="display:none">
       </div>
       <strong>
        1000
       </strong>
       results - showing
       <strong>
        1
       </strong>
       to
       <strong>
        20
       </strong>
       .
      </form>
      <section>
       <div class="alert alert-warning" role="alert">
        <strong>
         Warning!
        </strong>
        This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
       </div>
       <div>
        <ol class="row">
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/a-light-in-the-attic_1000/index.html">
             <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
            </a>
           </div>
           <p class="star-rating Three">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
             A Light in the ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £51.77
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/tipping-the-velvet_999/index.html">
             <img alt="Tipping the Velvet" class="thumbnail" src="media/cache/26/0c/260c6ae16bce31c8f8c95daddd9f4a1c.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/tipping-the-velvet_999/index.html" title="Tipping the Velvet">
             Tipping the Velvet
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £53.74
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/soumission_998/index.html">
             <img alt="Soumission" class="thumbnail" src="media/cache/3e/ef/3eef99c9d9adef34639f510662022830.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/soumission_998/index.html" title="Soumission">
             Soumission
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £50.10
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sharp-objects_997/index.html">
             <img alt="Sharp Objects" class="thumbnail" src="media/cache/32/51/3251cf3a3412f53f339e42cac2134093.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sharp-objects_997/index.html" title="Sharp Objects">
             Sharp Objects
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £47.82
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html">
             <img alt="Sapiens: A Brief History of Humankind" class="thumbnail" src="media/cache/be/a5/bea5697f2534a2f86a3ef27b5a8c12a6.jpg"/>
            </a>
           </div>
           <p class="star-rating Five">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/sapiens-a-brief-history-of-humankind_996/index.html" title="Sapiens: A Brief History of Humankind">
             Sapiens: A Brief History ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £54.23
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-requiem-red_995/index.html">
             <img alt="The Requiem Red" class="thumbnail" src="media/cache/68/33/68339b4c9bc034267e1da611ab3b34f8.jpg"/>
            </a>
           </div>
           <p class="star-rating One">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-requiem-red_995/index.html" title="The Requiem Red">
             The Requiem Red
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £22.65
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html">
             <img alt="The Dirty Little Secrets of Getting Your Dream Job" class="thumbnail" src="media/cache/92/27/92274a95b7c251fea59a2b8a78275ab4.jpg"/>
            </a>
           </div>
           <p class="star-rating Four">
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
            <i class="icon-star">
            </i>
           </p>
           <h3>
            <a href="catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html" title="The Dirty Little Secrets of Getting Your Dream Job">
             The Dirty Little Secrets ...
            </a>
           </h3>
           <div class="product_price">
            <p class="price_color">
             £33.34
            </p>
            <p class="instock availability">
             <i class="icon-ok">
             </i>
             In stock
            </p>
            <form>
             <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
              Add to basket
             </button>
            </form>
           </div>
          </article>
         </li>
         <li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
          <article class="product_pod">
           <div class="image_container">
            <a href="catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html">
             <img alt="The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull" class="thumbnail" src="media/cache/3d/54/3d54940e57e662c4dd1f3ff00c78cc64.jpg"/>

In [11]:
# Container of one book is "li" etc. Here using find_all so will return a list of 20 books 

books = soup.find_all("li", class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")

In [12]:
len(books)

20

In [13]:
# Selecting the first book 

book =books[0]
print (book.prettify())

<li class="col-xs-6 col-sm-4 col-md-3 col-lg-3">
 <article class="product_pod">
  <div class="image_container">
   <a href="catalogue/a-light-in-the-attic_1000/index.html">
    <img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
   </a>
  </div>
  <p class="star-rating Three">
   <i class="icon-star">
   </i>
   <i class="icon-star">
   </i>
   <i class="icon-star">
   </i>
   <i class="icon-star">
   </i>
   <i class="icon-star">
   </i>
  </p>
  <h3>
   <a href="catalogue/a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
    A Light in the ...
   </a>
  </h3>
  <div class="product_price">
   <p class="price_color">
    £51.77
   </p>
   <p class="instock availability">
    <i class="icon-ok">
    </i>
    In stock
   </p>
   <form>
    <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
     Add to basket
    </button>
   </form>
  </div>
 </article>
</li>

In [25]:
# Find title of the book 

Title = book.find("img")["alt"]
print (Title)

It's Only the Himalayas

In [ ]:

# Find price 
Price = book.find("p", class_="price_color").get_text()
print(Price)

£51.77

In [ ]:

# Find rating of the book <p class="star-rating Three">

Rating = book.find("p", class_="star-rating")
print (Rating["class"])

['star-rating', 'Three']

In [ ]:
Rating_value = rating["class"][1]
print(Rating_value)

Three

In [ ]:
# Make a dict with title, 

book_info = {}
book_info["Title"] = book.find("img")["alt"]
print(book_info)

{'Title': 'A Light in the Attic'}

In [ ]:
# Adding rating to the dict 

book_info["Rating"] = book.find("p", class_="star-rating")["class"][1] 
print(book_info)

{'Title': 'A Light in the Attic', 'Rating': 'Three'}

In [ ]:
# Adding price to the dict 

book_info["Price"] = book.find("p", class_="price_color").get_text()
print(book_info)

{'Title': 'A Light in the Attic', 'Rating': 'Three', 'Price': '£51.77'}

In [ ]:
# Make a list to scrap all books， put the one single book dict into this list

all_books = [] 
all_books.append(book_info)
print(all_books)

[{'Title': 'A Light in the Attic', 'Rating': 'Three', 'Price': '£51.77'}]

In [23]:
# Start looping to get all books 

all_books = []

for book in books: 
    book_info = {} 
    book_info["Title"] = book.find("img")["alt"]
    book_info["Rating"] = book.find("p", class_="star-rating")["class"][1]     
    book_info["Price"] = book.find("p", class_="price_color").get_text()  
    all_books.append(book_info)
len(all_books)
print(all_books)

[{'Title': 'A Light in the Attic', 'Rating': 'Three', 'Price': '£51.77'}, {'Title': 'Tipping the Velvet', 'Rating': 'One', 'Price': '£53.74'}, {'Title': 'Soumission', 'Rating': 'One', 'Price': '£50.10'}, {'Title': 'Sharp Objects', 'Rating': 'Four', 'Price': '£47.82'}, {'Title': 'Sapiens: A Brief History of Humankind', 'Rating': 'Five', 'Price': '£54.23'}, {'Title': 'The Requiem Red', 'Rating': 'One', 'Price': '£22.65'}, {'Title': 'The Dirty Little Secrets of Getting Your Dream Job', 'Rating': 'Four', 'Price': '£33.34'}, {'Title': 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull', 'Rating': 'Three', 'Price': '£17.93'}, {'Title': 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics', 'Rating': 'Four', 'Price': '£22.60'}, {'Title': 'The Black Maria', 'Rating': 'One', 'Price': '£52.15'}, {'Title': 'Starving Hearts (Triangular Trade Trilogy, #1)', 'Rating': 'Two', 'Price': '£13.99'}, {'Title': "Shakespeare's Sonnets", 'Rating': 'Four', 'Price': '£20.66'}, {'Title': 'Set Me Free', 'Rating': 'Five', 'Price': '£17.46'}, {'Title': "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)", 'Rating': 'Five', 'Price': '£52.29'}, {'Title': 'Rip it Up and Start Again', 'Rating': 'Five', 'Price': '£35.02'}, {'Title': 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991', 'Rating': 'Three', 'Price': '£57.25'}, {'Title': 'Olio', 'Rating': 'One', 'Price': '£23.88'}, {'Title': 'Mesaerion: The Best Science Fiction Stories 1800-1849', 'Rating': 'One', 'Price': '£37.59'}, {'Title': 'Libertarianism for Beginners', 'Rating': 'Two', 'Price': '£51.33'}, {'Title': "It's Only the Himalayas", 'Rating': 'Two', 'Price': '£45.17'}]

In [24]:
len(all_books)

20

In [26]:
book = books[0]
print(book.find("a"))

<a href="catalogue/a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>

In [27]:
book_link = book.find("a")["href"]
print(book_link)

catalogue/a-light-in-the-attic_1000/index.html

In [28]:
base_url = "https://books.toscrape.com/"

In [29]:
full_url = base_url + book_link
print (full_url)

https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html

In [30]:
detail_response = requests.get(full_url)
print (detail_response.status_code)

200

In [31]:
detail_soup = BeautifulSoup(detail_response.content, "html.parser")

In [35]:
print(detail_soup.prettify())

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en-us">
 <!--<![endif]-->
 <head>
  <title>
   A Light in the Attic | Books to Scrape - Sandbox
  </title>
  <meta content="text/html; charset=utf-8" http-equiv="content-type"/>
  <meta content="24th Jun 2016 09:29" name="created"/>
  <meta content="
    It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more
" name="description"/>
  <meta content="width=device-width" name="viewport"/>
  <meta content="NOARCHIVE,NOCACHE" name="robots"/>
  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
  <link href="../../static/oscar/favicon.ico" rel="shortcut icon"/>
  <link href="../../static/oscar/css/styles.css" rel="stylesheet" type="text/css"/>
  <link href="../../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.css" rel="stylesheet"/>
  <link href="../../static/oscar/css/datetimepicker.css" rel="stylesheet" type="text/css"/>
 </head>
 <body class="default" id="default">
  <header class="header container-fluid">
   <div class="page_inner">
    <div class="row">
     <div class="col-sm-8 h1">
      <a href="../../index.html">
       Books to Scrape
      </a>
      <small>
       We love being scraped!
      </small>
     </div>
    </div>
   </div>
  </header>
  <div class="container-fluid page">
   <div class="page_inner">
    <ul class="breadcrumb">
     <li>
      <a href="../../index.html">
       Home
      </a>
     </li>
     <li>
      <a href="../category/books_1/index.html">
       Books
      </a>
     </li>
     <li>
      <a href="../category/books/poetry_23/index.html">
       Poetry
      </a>
     </li>
     <li class="active">
      A Light in the Attic
     </li>
    </ul>
    <div id="messages">
    </div>
    <div class="content">
     <div id="promotions">
     </div>
     <div id="content_inner">
      <article class="product_page">
       <!-- Start of product page -->
       <div class="row">
        <div class="col-sm-6">
         <div class="carousel" id="product_gallery">
          <div class="thumbnail">
           <div class="carousel-inner">
            <div class="item active">
             <img alt="A Light in the Attic" src="../../media/cache/fe/72/fe72f0532301ec28892ae79a629a293c.jpg"/>
            </div>
           </div>
          </div>
         </div>
        </div>
        <div class="col-sm-6 product_main">
         <h1>
          A Light in the Attic
         </h1>
         <p class="price_color">
          £51.77
         </p>
         <p class="instock availability">
          <i class="icon-ok">
          </i>
          In stock (22 available)
         </p>
         <p class="star-rating Three">
          <i class="icon-star">
          </i>
          <i class="icon-star">
          </i>
          <i class="icon-star">
          </i>
          <i class="icon-star">
          </i>
          <i class="icon-star">
          </i>
          <!-- <small><a href="/catalogue/a-light-in-the-attic_1000/reviews/">


                    0 customer reviews

        </a></small>
         -->
          <!--
    <a id="write_review" href="/catalogue/a-light-in-the-attic_1000/reviews/add/#addreview" class="btn btn-success btn-sm">
        Write a review
    </a>

 -->
         </p>
         <hr/>
         <div class="alert alert-warning" role="alert">
          <strong>
           Warning!
          </strong>
          This is a demo website for web scraping purposes. Prices and ratings here were randomly assigned and have no real meaning.
         </div>
        </div>
        <!-- /col-sm-6 -->
       </div>
       <!-- /row -->
       <div class="sub-header" id="product_description">
        <h2>
         Product Description
        </h2>
       </div>
       <p>
        It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more
       </p>
       <div class="sub-header">
        <h2>
         Product Information
        </h2>
       </div>
       <table class="table table-striped">
        <tr>
         <th>
          UPC
         </th>
         <td>
          a897fe39b1053632
         </td>
        </tr>
        <tr>
         <th>
          Product Type
         </th>
         <td>
          Books
         </td>
        </tr>
        <tr>
         <th>
          Price (excl. tax)
         </th>
         <td>
          £51.77
         </td>
        </tr>
        <tr>
         <th>
          Price (incl. tax)
         </th>
         <td>
          £51.77
         </td>
        </tr>
        <tr>
         <th>
          Tax
         </th>
         <td>
          £0.00
         </td>
        </tr>
        <tr>
         <th>
          Availability
         </th>
         <td>
          In stock (22 available)
         </td>
        </tr>
        <tr>
         <th>
          Number of reviews
         </th>
         <td>
          0
         </td>
        </tr>
       </table>
       <section>
        <div class="sub-header" id="reviews">
        </div>
       </section>
      </article>
      <!-- End of product page -->
     </div>
    </div>
   </div>
  </div>
  <footer class="footer container-fluid">
  </footer>
  <!-- jQuery -->
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js">
  </script>
  <script>
   window.jQuery || document.write('<script src="../../static/oscar/js/jquery/jquery-1.9.1.min.js"><\/script>')
  </script>
  <!-- Twitter Bootstrap -->
  <script src="../../static/oscar/js/bootstrap3/bootstrap.min.js" type="text/javascript">
  </script>
  <!-- Oscar -->
  <script charset="utf-8" src="../../static/oscar/js/oscar/ui.js" type="text/javascript">
  </script>
  <script charset="utf-8" src="../../static/oscar/js/bootstrap-datetimepicker/bootstrap-datetimepicker.js" type="text/javascript">
  </script>
  <script charset="utf-8" src="../../static/oscar/js/bootstrap-datetimepicker/locales/bootstrap-datetimepicker.all.js" type="text/javascript">
  </script>
  <script type="text/javascript">
   $(function() {


    oscar.init();

            });
  </script>
  <!-- Version: N/A -->
 </body>
</html>

In [ ]:
# Scrap the UPC 

upc_row = detail_soup.find("th", string = "UPC")
print(upc_row)

<th>UPC</th>

The structure is like this: 
<tr>
    <th>UPC</th>
    <td>a897fe39b1053632</td>
</tr>
So we have to go back to the parent tag "tr"

In [37]:
upc_tr = upc_row.find_parent("tr")
print(upc_tr)

<tr>
<th>UPC</th><td>a897fe39b1053632</td>
</tr>

In [38]:
upc = upc_tr.find("td").get_text()
print(upc)

a897fe39b1053632

The struc of availability is: 
<tr>
         <th>
          Availability
         </th>
         <td>
          In stock (22 available)
         </td>
        </tr>

In [43]:
# Do the same for availability 

avai_row = detail_soup.find("th", string = "Availability")
print (avai_row)

<th>Availability</th>

In [44]:
availability = avai_row.find_parent("tr").find("td").get_text()
print(availability)

In stock (22 available)

You can also do this: 

rows = detail_soup.find_all("tr")

for row in rows:
    if row.find("th").get_text() == "Availability":
        availability = row.find("td").get_text()

Structure of genre
<ul class="breadcrumb">
     <li>
      <a href="../../index.html">
       Home
      </a>
     </li>
     <li>
      <a href="../category/books_1/index.html">
       Books
      </a>
     </li>
     <li>
      <a href="../category/books/poetry_23/index.html">
       Poetry
      </a>
     </li>
     <li class="active">
      A Light in the Attic
     </li>
    </ul>

In [48]:
# Do the same for genre 

genre_row = detail_soup.find("ul", class_="breadcrumb")
print(genre_row)

<ul class="breadcrumb">
<li>
<a href="../../index.html">Home</a>
</li>
<li>
<a href="../category/books_1/index.html">Books</a>
</li>
<li>
<a href="../category/books/poetry_23/index.html">Poetry</a>
</li>
<li class="active">A Light in the Attic</li>
</ul>

In [ ]:
genre = genre_row.find_all("a")[-1].get_text() # can also use [2] but [-1] is more estable, if they change the website's structure , genre usually is the -1 position 
print(genre)

Poetry

In [58]:
genre_row.find_all("a")

[<a href="../../index.html">Home</a>,
 <a href="../category/books_1/index.html">Books</a>,
 <a href="../category/books/poetry_23/index.html">Poetry</a>]

 Structure of Description 

 <div class="sub-header" id="product_description">
        <h2>
         Product Description
        </h2>
       </div>
<p>
       It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more
</p>

In [73]:
# Scrap Desription, <div and <p> are sibilings, <p> is not inside <div 

description_row = detail_soup.find("div", id="product_description")
print(description_row)

<div class="sub-header" id="product_description">
<h2>Product Description</h2>
</div>

In [75]:
description = description_row.find_next("p").get_text()
print (description)

It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love th It's hard to imagine a world without A Light in the Attic. This now-classic collection of poetry and drawings from Shel Silverstein celebrates its 20th anniversary with this special edition. Silverstein's humorous and creative verse can amuse the dowdiest of readers. Lemon-faced adults and fidgety kids sit still and read these rhythmic words and laugh and smile and love that Silverstein. Need proof of his genius? RockabyeRockabye baby, in the treetopDon't you know a treetopIs no safe place to rock?And who put you up there,And your cradle, too?Baby, I think someone down here'sGot it in for you. Shel, you never sounded so good. ...more

In [ ]:
# Now we have all information of a book, let's try to loop only getting the correct urls, instead of putting everything in the dict directly 

for book in books: 
    # 1. Get complete book links 
    book_link = book.find("a")["href"]
    full_url= base_url + book_link 
    print(full_url)

    # 2. Request detail page 
    detail_response = requests.get(full_url)

    if detail_response.status_code == 200: 
        print("success")

https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
success
https://books.toscrape.com/catalogue/tipping-the-velvet_999/index.html
success
https://books.toscrape.com/catalogue/soumission_998/index.html
success
https://books.toscrape.com/catalogue/sharp-objects_997/index.html
success
https://books.toscrape.com/catalogue/sapiens-a-brief-history-of-humankind_996/index.html
success
https://books.toscrape.com/catalogue/the-requiem-red_995/index.html
success
https://books.toscrape.com/catalogue/the-dirty-little-secrets-of-getting-your-dream-job_994/index.html
success
https://books.toscrape.com/catalogue/the-coming-woman-a-novel-based-on-the-life-of-the-infamous-feminist-victoria-woodhull_993/index.html
success
https://books.toscrape.com/catalogue/the-boys-in-the-boat-nine-americans-and-their-epic-quest-for-gold-at-the-1936-berlin-olympics_992/index.html
success
https://books.toscrape.com/catalogue/the-black-maria_991/index.html
success
https://books.toscrape.com/catalogue/starving-hearts-triangular-trade-trilogy-1_990/index.html
success
https://books.toscrape.com/catalogue/shakespeares-sonnets_989/index.html
success
https://books.toscrape.com/catalogue/set-me-free_988/index.html
success
https://books.toscrape.com/catalogue/scott-pilgrims-precious-little-life-scott-pilgrim-1_987/index.html
success
https://books.toscrape.com/catalogue/rip-it-up-and-start-again_986/index.html
success
https://books.toscrape.com/catalogue/our-band-could-be-your-life-scenes-from-the-american-indie-underground-1981-1991_985/index.html
success
https://books.toscrape.com/catalogue/olio_984/index.html
success
https://books.toscrape.com/catalogue/mesaerion-the-best-science-fiction-stories-1800-1849_983/index.html
success
https://books.toscrape.com/catalogue/libertarianism-for-beginners_982/index.html
success
https://books.toscrape.com/catalogue/its-only-the-himalayas_981/index.html
success

In [77]:
# request again but this time save them in a list so no need to request everytime running the loop 

responses = [] 

for book in books: 
    
    book_link = book.find("a")["href"]
    full_url= base_url + book_link 
    
    detail_response = requests.get(full_url)
    if detail_response.status_code == 200: 
        responses.append(detail_response)

In [ ]:
def scrape_books (min_rating, max_price): 

    all_books = []
    rating_map = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}

    for book, response in zip(books, responses): 
        book_info = {}
                       
        book_info["Title"] = book.find("img")["alt"]
        book_info["Rating"] = rating_map[book.find("p", class_="star-rating")["class"][1]]
        book_info["Price"] = float(book.find("p", class_="price_color").get_text().replace("£",""))   


        detail_soup = BeautifulSoup(response.content, "html.parser")

        upc_row = detail_soup.find("th", string = "UPC") 
        book_info["UPC"] = upc_row.find_parent("tr").find("td").get_text()

        avai_row = detail_soup.find("th", string = "Availability") 
        book_info["Availability"] = avai_row.find_parent("tr").find("td").get_text() 

        genre_row = detail_soup.find("ul", class_="breadcrumb") 
        book_info["Genre"] = genre_row.find_all("a")[-1].get_text() 

        description_row = detail_soup.find("div", id="product_description")
        book_info["Description"] = description_row.find_next("p").get_text()

                
        if book_info["Rating"] >= min_rating and book_info["Price"] <= max_price: 
            all_books.append(book_info) 
            
    return pd.DataFrame(all_books)

In [ ]:
scrape_books(5, 52)

# Only scrapes the main page, does not consider other categories.

Set Me Free 5 17.46
Rip it Up and Start Again 5 35.02

,Title,Rating,Price,UPC,Availability,Genre,Description
0,Set Me Free,5,17.46,ce6396b0f23f6ecc,In stock (19 available),Young Adult,Aaron Ledbetter’s future had been planned out ...
1,Rip it Up and Start Again,5,35.02,a34ba96d4081e6a4,In stock (19 available),Music,"Punk's raw power rejuvenated rock, but by the ..."

In [86]:
len(books)

20

In [ ]:
for book in books:
    print(book.find("img")["alt"])

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

In [105]:
# DRAFT 
all_book_elements = [] # whole page of books 
responses = []

for page_number in range(1,6):  # just practice with 5 pages instead of 50 
                
    pages_url = base_url + (f"catalogue/page-{page_number}.html")
    response = requests.get(pages_url) 
    soup = BeautifulSoup(response.content, "html.parser") 
    page_books = soup.find_all("li", class_="col-xs-6 col-sm-4 col-md-3 col-lg-3")
    all_book_elements.extend(page_books) 
                 

for book in all_book_elements: 
    book_link = book.find("a")["href"] # get a book's link 
    full_url = base_url + "catalogue/" + book_link
    detail_response = requests.get(full_url)

    if detail_response.status_code == 200: 
        responses.append(detail_response)

In [106]:
print(len(all_book_elements))
print(len(responses))

100
100

In [92]:
print (base_url)
print(book.find("a")["href"]) # Book's name is: its-only-the-himalayas_981

https://books.toscrape.com/
catalogue/its-only-the-himalayas_981/index.html

In [109]:
# DRAFT, DON'T RUN ! 

def scrape_books (min_rating, max_price): 
    """
    This function only scrapes book data from the first 5 pages of the main catalogue. 
    Parameters: 
    min_rating(int): minimum book rating 
    max_price (float): maximum price 

    Returns: 
    panda DataFrame, filtered by book info including title, rating, price, genre, 
    UPC and description. 
     
      
    """

    all_books = []
    
    rating_map = {"One": 1, "Two": 2, "Three": 3, "Four": 4, "Five": 5}

    for book, response in zip(all_book_elements, responses):
        
        book_info = {}

        detail_soup = BeautifulSoup(response.content, "html.parser")

        book_info["Title"] = book.find("img")["alt"]
        book_info["Rating"] = rating_map[book.find("p", class_="star-rating")["class"][1]]
        book_info["Price"] = float(book.find("p", class_="price_color").get_text().replace("£",""))   
        
        upc_row = detail_soup.find("th", string = "UPC") 
        book_info["UPC"] = upc_row.find_parent("tr").find("td").get_text()

        avai_row = detail_soup.find("th", string = "Availability") 
        book_info["Availability"] = avai_row.find_parent("tr").find("td").get_text() 

        genre_row = detail_soup.find("ul", class_="breadcrumb") 
        book_info["Genre"] = genre_row.find_all("a")[-1].get_text() 

        description_row = detail_soup.find("div", id="product_description")
        book_info["Description"] = description_row.find_next("p").get_text()

                
        if book_info["Rating"] >= min_rating and book_info["Price"] <= max_price: 
            all_books.append(book_info) 
            
    return pd.DataFrame(all_books)

In [111]:
help(scrape_books)

Help on function scrape_books in module __main__:

scrape_books(min_rating, max_price)
    This function only scrapes book data from the first 5 pages of the main catalogue.
    Parameters:
    min_rating(int): minimum book rating
    max_price (float): maximum price

    Returns:
    panda DataFrame, filtered by book info including title, rating, price, genre,
    UPC and description.

In [ ]:
scrape_books (5, 50)

,Title,Rating,Price,UPC,Availability,Genre,Description
0,Set Me Free,5,17.46,ce6396b0f23f6ecc,In stock (19 available),Young Adult,Aaron Ledbetter’s future had been planned out ...
1,Rip it Up and Start Again,5,35.02,a34ba96d4081e6a4,In stock (19 available),Music,"Punk's raw power rejuvenated rock, but by the ..."
2,Chase Me (Paris Nights #2),5,25.27,c2e46a2ee3b4a322,In stock (19 available),Romance,"A Michelin two-star chef at twenty-eight, Viol..."
3,Black Dust,5,34.53,00bfed9e18bb36f3,In stock (19 available),Romance,"No matter how busy he keeps himself, successfu..."
4,Worlds Elsewhere: Journeys Around Shakespeare’...,5,40.30,4c28def39d850cdf,In stock (18 available),Nonfiction,"Anti-apartheid activist, Bollywood screenwrite..."
5,The Four Agreements: A Practical Guide to Pers...,5,17.66,6258a1f6a6dcfe50,In stock (18 available),Spirituality,"In The Four Agreements, don Miguel Ruiz reveal..."
6,The Elephant Tree,5,23.82,5dada2b7be26bd03,In stock (18 available),Thriller,Mark Fallon is an overworked detective investi...
7,Sophie's World,5,15.94,6be3beb0793a53e7,In stock (18 available),Philosophy,A page-turning novel that is also an explorati...
8,Private Paris (Private #10),5,47.61,b12b89017878a60d,In stock (17 available),Fiction,Paris is burning--and only Private's Jack Morg...
9,#HigherSelfie: Wake Up Your Life. Free Your So...,5,23.11,c27f6e1f185b0383,In stock (17 available),Nonfiction,There is a cosmic alarm clock going off around...
10,Thirst,5,17.27,709822d0b5bcb7f4,In stock (16 available),Fiction,"On a searing summer Friday, Eddie Chapman has ..."
11,The Inefficiency Assassin: Time Management Tac...,5,20.59,8c9e6bf2467d740d,In stock (16 available),Default,"Slay Procrastination, Distraction, and Overwhe..."
12,The Activist's Tao Te Ching: Ancient Advice fo...,5,32.24,7d6d2a6c0276f81b,In stock (16 available),Spirituality,Change and anger are in the air. Looking for a...
13,"Princess Jellyfish 2-in-1 Omnibus, Vol. 01 (Pr...",5,13.61,0fa6dceead7ce47a,In stock (16 available),Sequential Art,THE LONG-AWAITED STORY OF FANGIRLS TAKING ON T...
14,Princess Between Worlds (Wide-Awake Princess #5),5,13.34,0e691eda369f4e09,In stock (16 available),Fantasy,Just as Annie and Liam are busy making plans t...
15,Join,5,35.67,18ad3ed896c7ce05,In stock (16 available),Science Fiction,What if you could live multiple lives simultan...